### ISSUE TITLE
Error: spawn java ENOENT

### ISSUE THREAD

**Issue by scottansell** [dominicbarnes/node-minecraft-runner#7]
When running my index.js script I get the following error. I'm on OSX but I've had the exact same issue on Windows earlier.

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn java ENOENT
    at exports._errnoException (util.js:953:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Function.Module.runMain (module.js:577:11)
    at startup (node.js:160:18)
    at node.js:449:3
```

**Comment by RicoswLive** [comment]
Maybe can't access the server.jar ?
